name: Bot

on:
  push:
    paths:
      - "bot/**"
      - ".github/workflows/bot.yml"
  pull_request:
    paths:
      - "bot/**"
      - ".github/workflows/bot.yml"

permissions:
  contents: read

defaults:
  run:
    working-directory: ./bot

env:
  GO_VERSION: 1.24.6
  LINT_VERSION: v2.2.2

jobs:
  test_job:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: |
            bot/go.sum
      - name: test
        run: make test

  vuln_job:
    name: vuln
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: |
            bot/go.sum
      - name: vuln
        run: make vuln

  lint_job:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: |
            bot/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ env.LINT_VERSION }}
          working-directory: ./bot
